### ISSUE TITLE
地图如何导入进去？

### ISSUE THREAD

**Issue by KaiJia2017** [w3lik/lik-pack#5]
之前h-lua，把地图资源放入resource就好了，很简单
![image](https://github.com/w3lik/likRC/assets/32702706/c54452cb-fade-4881-8e54-ddc663ee23bb)

现在导入别的地图资源到resource下就不生效了，也不清楚怎么放。如果要放，还要加代码，很不方便
![image](https://github.com/w3lik/likRC/assets/32702706/e21020aa-4554-496b-809b-323e1b164773)

**Comment by hunzsig** [comment]
一样放map/resource就好了
